### ISSUE TITLE
Slack?

### ISSUE THREAD

**Issue by niccokunzmann** [schulcloud/schulcloud-client#98]
Es gibt ein Slack laut #97.
Ist das offen, kann man da rein?
Es gibt EInladesoftware recht bequem auf Heroku. Beispiel: https://coderdojopotsdam.herokuapp.com/
Ich fände das cool für der ersten Kontakt zu Schulcloud und man kann es als Admin recht leicht aufsetzen.

https://github.com/avinassh/slackipy

**Comment by jprberlin** [comment]
Das Slack ist moments nur HPI intern. Es als generelles Kommunikationsmedium zu promoten finde ich aus Datenschutz gründen problematisch...

**Comment by niccokunzmann** [comment]
ok.
